name: Test in New Recruit
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system to horus-heresy
        uses: actions/checkout@v4
        with:
          path: horus-heresy
      - name: Store CWD in environment variable
        run: DEFAULT_DATA_DIRECTORY=$(pwd)
      - name: Checking out bscopy
        uses: actions/checkout@v4
        with:
          repository: nstephenh/bscopy
          path: BSCopy
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable
      - name: Install google chrome stable
        run: sudo apt install google-chrome-stable
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install webdriver-manager selenium
      - name: ls to show present files
        run: ls
      - name: ls to show present files in BSCopy
        run: ls BSCopy
      - name: Run tests
        run: python3 system/tests/test_game.py
        working-directory: ./BSCopy
