name: Run Selenium On GitHub Action
on: [ push, pull_request ]
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system
        uses: actions/checkout@v3
      - name: Checking out bscopy
        uses: actions/checkout@v3
        with:
          repository: nstephenh/bscopy
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install webdriver-manager selenium


      - name: Running the Python script
        run: python3 BSCopy/system/tests/test_game.py
