name: Test in New Recruit
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system to horus-heresy
        uses: actions/checkout@v4
        with:
          path: horus-heresy
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installing package list
        run: apt list --installed
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install webdriver-manager selenium
      - name: Run tests
        run: python3 tests.py
        working-directory: horus-heresy/tests/
        env:
          DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}
