name: Test in New Recruit
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system to horus-heresy
        uses: actions/checkout@v4
        with:
          path: horus-heresy
      - name: Checking out bscopy
        uses: actions/checkout@v4
        with:
          repository: nstephenh/bscopy
          path: BSCopy
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installing package list
        run: apt list --installed
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install webdriver-manager selenium
      - name: Print workspace directory (as that's where we checked out data)
        run: echo $DEFAULT_DATA_DIRECTORY
        env:
          DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}

      - name: Run tests
        run: python3 system/tests/test_game.py
        working-directory: ./BSCopy
        env:
          DEFAULT_DATA_DIRECTORY: ${{ github.workspace }}
